import 'server-only';
import { createHash } from 'node:crypto';
import { strToU8, zipSync, type Zippable } from 'fflate';
import subsetFont from 'subset-font';
import svg2ttf from 'svg2ttf';
import SvgPath from 'svgpath';
import { badRequest } from '@/lib/http';
import { className, hex, IconFontConfigSchema, toFontelloConfig, validateConfig, type IconFontConfig } from './config';
import { renderIconDemo } from './demo';
import { getSetGlyph, listSets, type IconSet } from './sets';

export const UNITS_PER_EM = 1000;
export const ASCENT = 850;
export const DESCENT = -150;

export interface ResolvedGlyph {
  uid: string;
  css: string;
  code: number;
  src: string;
  d: string;
  width: number;
}

const esc = (s: string) => s.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);

/** Fill in outlines for bundled icons and check the config can be built. */
export async function resolveConfig(input: unknown): Promise<{ config: IconFontConfig; glyphs: ResolvedGlyph[]; sets: IconSet[] }> {
  const config = IconFontConfigSchema.parse(input);
  const errors = validateConfig(config);
  if (errors.length) throw badRequest(errors[0], { errors });
  const glyphs: ResolvedGlyph[] = [];
  const missing: string[] = [];
  for (const g of config.glyphs) {
    let d = g.d;
    let width = g.width;
    if (!d) {
      const found = await getSetGlyph(g.uid);
      if (!found) {
        missing.push(g.css);
        continue;
      }
      d = found.d;
      width = found.width;
    }
    const parsed = new SvgPath(d);
    if ((parsed as unknown as { err: string }).err) throw badRequest(`The outline of “${g.css}” is not a valid SVG path.`);
    glyphs.push({ uid: g.uid, css: g.css, code: g.code, src: g.src, d, width: Math.round(width ?? UNITS_PER_EM) });
  }
  if (missing.length) throw badRequest(`Unknown icons: ${missing.slice(0, 5).join(', ')}${missing.length > 5 ? '…' : ''}. Upload their SVGs again.`, { missing });
  const all = await listSets();
  const used = new Set(glyphs.map((g) => g.src));
  return { config: { ...config, glyphs: config.glyphs.map((g, i) => ({ ...g, d: glyphs[i].d, width: glyphs[i].width })) }, glyphs, sets: all.filter((s) => used.has(s.id)) };
}

/** An SVG font, the input format of svg2ttf. Outlines are flipped into font space (y up, baseline at 0). */
export function svgFont(name: string, glyphs: ResolvedGlyph[]) {
  const rows = glyphs.map((g) => {
    const d = new SvgPath(g.d).scale(1, -1).translate(0, ASCENT).abs().round(1).toString();
    return `<glyph glyph-name="${esc(g.css)}" unicode="&#x${hex(g.code)};" d="${d}" horiz-adv-x="${g.width}"/>`;
  });
  return `<?xml version="1.0" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg"><defs><font id="${esc(name)}" horiz-adv-x="${UNITS_PER_EM}">
<font-face font-family="${esc(name)}" font-weight="400" font-stretch="normal" units-per-em="${UNITS_PER_EM}" ascent="${ASCENT}" descent="${DESCENT}"/>
<missing-glyph horiz-adv-x="${UNITS_PER_EM}"/>
${rows.join('\n')}
</font></defs></svg>`;
}

export interface IconFontFiles {
  ttf: Uint8Array;
  woff: Uint8Array;
  woff2: Uint8Array;
  /** Short content hash, for cache-busting URLs. */
  hash: string;
}

export async function buildFontFiles(name: string, glyphs: ResolvedGlyph[]): Promise<IconFontFiles> {
  let ttf: Uint8Array;
  try {
    ttf = svg2ttf(svgFont(name, glyphs), {
      copyright: 'Generated by Typeface Hub',
      description: `${name} icon font`,
      version: '1.0',
      ts: 0, // deterministic output: the same icons always give the same files
    }).buffer;
  } catch (e) {
    throw badRequest(`Could not build the font: ${(e as Error).message}`);
  }
  ttf = new Uint8Array(ttf);
  const text = String.fromCodePoint(...glyphs.map((g) => g.code));
  const [woff2, woff] = await Promise.all(
    (['woff2', 'woff'] as const).map(async (targetFormat) => new Uint8Array(await subsetFont(Buffer.from(ttf), text, { targetFormat, preserveNameIds: [0, 1, 2, 3, 4, 5, 6] }))),
  );
  return { ttf, woff, woff2, hash: createHash('sha256').update(ttf).digest('hex').slice(0, 10) };
}

/** Selector that matches every icon class, e.g. [class^="icon-"]:before, [class*=" icon-"]:before. */
export function baseSelector(cfg: Pick<IconFontConfig, 'prefix' | 'suffix'>) {
  return cfg.suffix ? `[class$="${cfg.prefix}"]:before, [class*="${cfg.prefix} "]:before` : `[class^="${cfg.prefix}"]:before, [class*=" ${cfg.prefix}"]:before`;
}

export function codesCss(cfg: Pick<IconFontConfig, 'prefix' | 'suffix'>, glyphs: { css: string; code: number }[]) {
  return glyphs.map((g) => `.${className(cfg, g.css)}:before { content: '\\${hex(g.code)}'; } /* '${String.fromCodePoint(g.code)}' */`).join('\n');
}

/** The complete icon stylesheet: @font-face, the shared rule for every icon, and one rule per icon. */
export function iconCss(cfg: Pick<IconFontConfig, 'name' | 'prefix' | 'suffix'>, glyphs: { css: string; code: number }[], src: { woff2: string; woff?: string; ttf?: string }, header = '') {
  const sources = [`url('${src.woff2}') format('woff2')`, src.woff && `url('${src.woff}') format('woff')`, src.ttf && `url('${src.ttf}') format('truetype')`].filter(Boolean);
  return `${header}@font-face {
  font-family: '${cfg.name}';
  src: ${sources.join(',\n       ')};
  font-weight: normal;
  font-style: normal;
  font-display: block;
}

${baseSelector(cfg)} {
  font-family: '${cfg.name}';
  font-style: normal;
  font-weight: normal;
  speak: never;
  display: inline-block;
  width: 1em;
  text-align: center;
  text-decoration: inherit;
  font-variant: normal;
  text-transform: none;
  line-height: 1em;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

${codesCss(cfg, glyphs)}
`;
}

function licenceText(sets: IconSet[], hasCustom: boolean) {
  const lines = ['Icons in this font', '==================', ''];
  for (const s of sets) {
    lines.push(s.name, s.copyright ? `  ${s.copyright}` : '', s.author ? `  Author:   ${s.author}` : '', s.license ? `  Licence:  ${s.license}${s.licenseUrl ? ` (${s.licenseUrl})` : ''}` : '', s.homepage ? `  Homepage: ${s.homepage}` : '', '');
  }
  if (hasCustom) lines.push('Custom icons', '  Uploaded by you. Make sure you have the right to use them.', '');
  lines.push('Check each licence before use: some require attribution (for example CC BY).', '');
  return lines.filter((l, i, a) => l !== '' || a[i - 1] !== '').join('\n');
}

export interface BuiltIconKit {
  filename: string;
  zip: Uint8Array;
  files: IconFontFiles;
  glyphs: ResolvedGlyph[];
  config: IconFontConfig;
}

/**
 * Build a Fontello-style kit: font/ (WOFF2, WOFF, TTF), css/ (the stylesheet,
 * codes only, and a variant with the font embedded), demo.html, config.json
 * (opens again in Typeface Hub or Fontello), LICENSE.txt and README.md.
 */
export async function buildIconKit(input: unknown): Promise<BuiltIconKit> {
  const { config, glyphs, sets } = await resolveConfig(input);
  const files = await buildFontFiles(config.name, glyphs);
  const n = config.name;
  const header = `/* ${n} icon font · ${glyphs.length} icon${glyphs.length === 1 ? '' : 's'} · generated by Typeface Hub */\n`;
  const css = iconCss(config, glyphs, { woff2: `../font/${n}.woff2?${files.hash}`, woff: `../font/${n}.woff?${files.hash}`, ttf: `../font/${n}.ttf?${files.hash}` }, header);
  const embedded = iconCss(config, glyphs, { woff2: `data:font/woff2;base64,${Buffer.from(files.woff2).toString('base64')}` }, header);
  const fontelloSets = new Set(sets.filter((s) => s.source === 'fontello').map((s) => s.id));
  const exported = toFontelloConfig(config, (src) => fontelloSets.has(src));

  const tree: Zippable = {
    font: {
      [`${n}.woff2`]: [files.woff2, { level: 0 }],
      [`${n}.woff`]: [files.woff, { level: 0 }],
      [`${n}.ttf`]: files.ttf,
    },
    css: {
      [`${n}.css`]: strToU8(css),
      [`${n}-codes.css`]: strToU8(header + codesCss(config, glyphs) + '\n'),
      [`${n}-embedded.css`]: strToU8(embedded),
    },
    'demo.html': strToU8(renderIconDemo({ config, glyphs, cssFile: `css/${n}.css` })),
    'config.json': strToU8(JSON.stringify(exported, null, 2) + '\n'),
    'LICENSE.txt': strToU8(licenceText(sets, glyphs.some((g) => g.src === 'custom'))),
    'README.md': strToU8(readme(config, glyphs)),
  };
  const zip = zipSync({ [`${n}-icons`]: tree }, { level: 6 });
  return { filename: `${n}-icons.zip`, zip, files, glyphs, config };
}

function readme(cfg: IconFontConfig, glyphs: ResolvedGlyph[]) {
  const first = glyphs[0];
  const cls = className(cfg, first.css);
  return `# ${cfg.name} icon font

${glyphs.length} icon${glyphs.length === 1 ? '' : 's'}, generated by Typeface Hub.

| Path | What it is |
| --- | --- |
| \`font/${cfg.name}.woff2\`, \`.woff\`, \`.ttf\` | The font |
| \`css/${cfg.name}.css\` | \`@font-face\`, the shared icon rule and one class per icon |
| \`css/${cfg.name}-codes.css\` | Only the per-icon rules, to combine with your own \`@font-face\` |
| \`css/${cfg.name}-embedded.css\` | The same stylesheet with the WOFF2 font embedded (no separate font file) |
| \`demo.html\` | Every icon with its class and code; click one to copy it |
| \`config.json\` | This font's definition. Open it in Typeface Hub (or Fontello) to add or change icons |
| \`LICENSE.txt\` | Licences of the icon sets used |

## Use it

Copy \`font/\` and \`css/\` into your site and link the stylesheet:

\`\`\`html
<link rel="stylesheet" href="/css/${cfg.name}.css">

<i class="${cls}" aria-hidden="true"></i>
<button aria-label="${first.css}"><i class="${cls}" aria-hidden="true"></i></button>
\`\`\`

Icons take the current text colour and font size, so style them like text:

\`\`\`css
.${cls} { color: #0f766e; font-size: 24px; }
\`\`\`

In React or Next.js, import the stylesheet once (for example in your root layout) and use \`<i className="${cls}" aria-hidden="true" />\`.

Icons are decorative to screen readers (\`speak: never\`). Give buttons and links that only show an icon an \`aria-label\`.

## Codes

${glyphs.map((g) => `- \`${className(cfg, g.css)}\`: U+${hex(g.code).toUpperCase()}`).join('\n')}
`;
}
