import { className, hex, type IconFontConfig } from './config';

/** demo.html for an icon kit: a searchable grid of every icon with its class and code. Works offline. */
export function renderIconDemo({ config, glyphs, cssFile }: { config: IconFontConfig; glyphs: { css: string; code: number }[]; cssFile: string }) {
  const esc = (s: string) => s.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
  const cells = glyphs
    .map((g) => {
      const cls = className(config, g.css);
      return `<button class="cell" data-name="${esc(g.css)}" data-class="${esc(cls)}" title="Copy class"><i class="${esc(cls)}" aria-hidden="true"></i><span class="name">${esc(cls)}</span><span class="code">U+${hex(g.code).toUpperCase()}</span></button>`;
    })
    .join('\n');
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(config.name)} icons</title>
<link rel="stylesheet" href="${esc(cssFile)}">
<style>
  :root { --bg: #fff; --fg: #18181b; --muted: #71717a; --line: #e4e4e7; --card: #fafafa; --accent: #0f766e; }
  @media (prefers-color-scheme: dark) { :root { --bg: #09090b; --fg: #fafafa; --muted: #a1a1aa; --line: #27272a; --card: #18181b; --accent: #2dd4bf; } }
  * { box-sizing: border-box; }
  body { margin: 0; font: 14px/1.5 system-ui, sans-serif; background: var(--bg); color: var(--fg); }
  header { position: sticky; top: 0; background: var(--bg); border-bottom: 1px solid var(--line); padding: 16px 24px; display: flex; flex-wrap: wrap; gap: 12px; align-items: center; z-index: 1; }
  h1 { font-size: 18px; margin: 0 auto 0 0; }
  h1 small { color: var(--muted); font-weight: 400; margin-left: 6px; }
  input[type=search] { font: inherit; padding: 6px 10px; border: 1px solid var(--line); border-radius: 8px; background: var(--card); color: inherit; width: 220px; }
  label { color: var(--muted); display: flex; gap: 8px; align-items: center; }
  main { padding: 24px; display: grid; grid-template-columns: repeat(auto-fill, minmax(150px, 1fr)); gap: 10px; }
  .cell { font: inherit; color: inherit; background: var(--card); border: 1px solid var(--line); border-radius: 10px; padding: 18px 8px 12px; display: flex; flex-direction: column; align-items: center; gap: 6px; cursor: pointer; }
  .cell:hover { border-color: var(--accent); }
  .cell i { font-size: var(--size, 32px); color: var(--accent); }
  .name { font: 12px ui-monospace, monospace; word-break: break-all; text-align: center; }
  .code { font-size: 11px; color: var(--muted); }
  .copied .name::after { content: ' ✓'; color: var(--accent); }
  footer { color: var(--muted); padding: 0 24px 32px; }
  code { font-family: ui-monospace, monospace; }
</style>
</head>
<body>
<header>
  <h1>${esc(config.name)}<small>${glyphs.length} icons</small></h1>
  <input type="search" id="q" placeholder="Search icons" aria-label="Search icons">
  <label>Size <input type="range" id="size" min="12" max="96" value="32" aria-label="Icon size"></label>
</header>
<main id="grid">
${cells}
</main>
<footer>Use an icon with <code>&lt;i class="${esc(glyphs[0] ? className(config, glyphs[0].css) : '')}" aria-hidden="true"&gt;&lt;/i&gt;</code>. Click an icon to copy its class. Generated by Typeface Hub.</footer>
<script>
  const q = document.getElementById('q');
  const cells = [...document.querySelectorAll('.cell')];
  q.addEventListener('input', () => { const t = q.value.toLowerCase().trim(); cells.forEach((c) => { c.hidden = t && !c.dataset.name.includes(t); }); });
  document.getElementById('size').addEventListener('input', (e) => document.documentElement.style.setProperty('--size', e.target.value + 'px'));
  cells.forEach((c) => c.addEventListener('click', async () => {
    try { await navigator.clipboard.writeText(c.dataset.class); } catch {}
    c.classList.add('copied'); setTimeout(() => c.classList.remove('copied'), 1200);
  }));
</script>
</body>
</html>
`;
}
